### ISSUE TITLE
Make h1 more prominent and aesthetic.

### ISSUE THREAD

**Issue by andrew-sipes** [krupapatell/project-four#2]
![better-h1](https://user-images.githubusercontent.com/25012869/99755494-eccae100-2ab8-11eb-95be-b62fefd85947.png)

```css
h1 {
    background: ???????;
    color: ???????;
    margin-top: ???????;
    min-height: ???????;
    display: ???????;
    align-items: ???????;
    justify-content: ???????;
}
```
