### ISSUE TITLE
Style the button so that it matches your site.

### ISSUE THREAD

**Issue by andrew-sipes** [krupapatell/project-four#3]
![better-button](https://user-images.githubusercontent.com/25012869/99755663-4c28f100-2ab9-11eb-88d9-299840f643f4.png)

```css
.myBtn {
  color: ??????;
  border-radius: ??????;
  border: ??????;
  background: ??????;
  padding: ??????;
  width: ??????;
  max-width: ??????;
  margin: ??????;
  display: ??????;
}
```
