### ISSUE TITLE
Set a maximum width on the chart such that it matches the width of your slideshow.

### ISSUE THREAD

**Issue by andrew-sipes** [krupapatell/project-four#4]
![better-chart](https://user-images.githubusercontent.com/25012869/99755818-b8a3f000-2ab9-11eb-81b4-519f10e55ef9.png)

```css
.flourish {
  max-width: ??????;
  margin: ?? ??;
}
```
